#!/usr/bin/env bash

apt-get update
apt-get install -y git python3 libfreetype6-dev libpng12-dev python3-setuptools python3-dev pkg-config python3-numpy python3-scipy r-base libzmq3-dev
sudo easy_install3 pip
echo "alias python='python3'" >> ~/.bashrc
echo "alias pip='pip3'" >> ~/.bashrc
echo "alias ipython='ipython3'" >> ~/.bashrc
echo "alias easy_install='easy_install3'" >> ~/.bashrc
source ~/.bashrc

echo "alias python='python3'" >> /home/vagrant/.bashrc
echo "alias pip='pip3'" >> /home/vagrant/.bashrc
echo "alias ipython='ipython3'" >> /home/vagrant/.bashrc
echo "alias easy_install='easy_install3'" >> /home/vagrant/.bashrc

pip3 install networkx ipython matplotlib pandas seaborn igraph jupyter metaknowledge#Add to pip here

mkdir -p /vagrant/vagrant/logs/

echo "#!/bin/bash" > /etc/rc.local
echo "while [ ! -d /vagrant/vagrant/profile_wosserver ] ; do sleep 1 ; done" >> /etc/rc.local
echo "/usr/local/bin/jupyter-notebook --no-browser --ProfileDir.location=/vagrant/vagrant/profile_wosserver --ip='*' --port=8888 --notebook-dir=/notebooks 2>&1 | tee -a /vagrant/vagrant/logs/ipythonNoteBook.log /home/vagrant/ipythonNoteBook.log &" >> /etc/rc.local
echo "echo 'Starting Notebook server'" >> /etc/rc.local
echo "echo 'Pulling metaknowledge'" >> /etc/rc.local
echo "git -C /vagrant pull" >> /etc/rc.local
echo "echo 'Updating python packages'" >> /etc/rc.local
echo "pip3 install --upgrade  networkx ipython matplotlib pandas seaborn igraph jupyter metaknowledge"
echo "exit 0" >> /etc/rc.local
sudo chown root /etc/rc.local
sudo chmod 755 /etc/rc.local

echo "#!/bin/bash -e" > /home/vagrant/ipythonStartup.sh
echo "/etc/rc.local" >> /home/vagrant/ipythonStartup.sh
chmod +x /home/vagrant/ipythonStartup.sh

/etc/rc.local

echo "provisioning done"
echo "Notebook Server running at http://localhost:1159"
