#!/usr/bin/env bash

apt-get update
apt-get install -y git python3 python3 libfreetype6-dev libpng12-dev python3-setuptools python3-dev pkg-config python3-numpy python3-scipy
sudo easy_install3 pip
echo "alias python='python3'" >> ~/.bashrc
echo "alias pip='pip3'" >> ~/.bashrc
echo "alias ipython='ipython3'" >> ~/.bashrc
echo "alias easy_install='easy_install3'" >> ~/.bashrc
source ~/.bashrc

echo "alias python='python3'" >> /home/vagrant/.bashrc
echo "alias pip='pip3'" >> /home/vagrant/.bashrc
echo "alias ipython='ipython3'" >> /home/vagrant/.bashrc
echo "alias easy_install='easy_install3'" >> /home/vagrant/.bashrc

#easy_install -U distribute
pip3 install networkx "ipython[notebook]" matplotlib
git clone https://github.com/mclevey/web_of_science_isi.git
cd web_of_science_isi/isilib/
python3 setup.py install
cd ../..

mkdir -p /home/vagrant/.ipython/
cp -r /vagrant/profile_wosserver /home/vagrant/.ipython/
chown vagrant /home/vagrant/.ipython/ -R

cp -r /home/vagrant/.ipython/ /root/
chown root /root/.ipython/ -R

chmod +x /etc/rc.local
echo "#!/bin/bash" > /etc/rc.local
echo "/usr/local/bin/ipython3 notebook --no-browser --ProfileDir.location=/vagrant/profile_wosserver --profile=wosserver 2>&1 | tee /vagrant/ipythonNoteBook.log" >> /etc/rc.local
echo "exit 0" >> /etc/rc.local

echo "#!/bin/bash" > /home/vagrant/ipythonStartup.sh
echo "/etc/rc.local" >> /home/vagrant/ipythonStartup.sh
echo "echo 'Starting ipython server'" >> /home/vagrant/ipythonStartup.sh
chmod +x /home/vagrant/ipythonStartup.sh

/etc/rc.local &

echo "provisioning done"

#mkdir -p /home/vagrant/.crontab
#echo "@reboot /home/vagrant/ipythonStartup.sh" > /home/vagrant/.crontab/vagrant.cron

#crontab -u vagrant /home/vagrant/.crontab/vagrant.cron
#crontab -u root /home/vagrant/.crontab/vagrant.cron


#/home/vagrant/ipythonStartup.sh
