# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|


   config.vm.provider "virtualbox" do |vb, override|
     config.vm.box = "ubuntu/trusty64"
     override.vm.box_url = "https://atlas.hashicorp.com/ubuntu/trusty64"
     vb.name = "Networks_Labs"
     vb.memory = "2048"
     override.vm.network :forwarded_port, host: 1159, guest: 8888, auto_correct: true
   end
   config.ssh.insert_key = false
   config.vm.synced_folder ".", "/vagrant", disabled: true
   config.vm.synced_folder '..', "/vagrant"
   config.vm.synced_folder '../notebooks', "/notebooks"
   config.vm.provision :shell, path: "bootstrap"

end
