# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|


   config.vm.provider "virtualbox" do |vb, override|
      config.vm.box = "ubuntu/trusty64"
      override.vm.box_url = "https://atlas.hashicorp.com/ubuntu/trusty64"
     # Display the VirtualBox GUI when booting the machine
     #vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "1024"
     override.vm.network :forwarded_port, host: 8888, guest: 8888, auto_correct: true
   end
   #config.ssh.username = "student"
   #config.ssh.password = "password"
   config.ssh.insert_key = false
   config.vm.synced_folder ".", "/vagrant", disabled: true
   config.vm.synced_folder '..', "/vagrant"
   config.vm.synced_folder '../notebooks', "/notebooks"
   #config.ssh.private_key_path = "isilib"
   config.vm.provision :shell, path: "bootstrap"

end
