from ...WOS.tagProcessing.helpFuncs import makeBiDirectional


authorBasedTags = [
    'AD',
    'AUID',
]

tagNameDict = {
"Abstract" : "AB",
"Copyright Information" : "CI",
"Affiliation" : "AD",
"Investigator Affiliation" : "IRAD",
"Article Identifier" : "AID",
"authorsShort" : "AU",
"Author Identifier" : "AUID",
"authorsFull" : "FAU",
"Book Title" : "BTI",
"Collection Title" : "CTI",
"Corporate Author" : "CN",
"Create Date" : "CRDT",
"Date Completed" : "DCOM",
"Date Created" : "DA",
"Date Last Revised" : "LR",
"Date of Electronic Publication" : "DEP",
"Date of Publication" : "DP",
"Edition" : "EN",
"Editor and Full Editor Name" : "ED",
"Editor and Full Editor Name" : "FED",
"Entrez Date" : "EDAT",
"Gene Symbol" : "GS",
"General Note" : "GN",
"Grant Number" : "GR",
"Investigator Name and Full Investigator Name" : "IR",
"Investigator Name and Full Investigator Name" : "FIR",
"ISBN" : "ISBN",
"ISSN" : "IS",
"Issue" : "IP",
"Journal Title Abbreviation" : "TA",
"Journal Title" : "JT",
"Language" : "LA",
"Location Identifier" : "LID",
"Manuscript Identifier" : "MID",
"MeSH Date" : "MHDA",
"MeSH Terms" : "MH",
"NLM Unique ID" : "JID",
"Number of References" : "RF",
"Other Abstract and Other Abstract Language" : "OAB",
"Other Abstract and Other Abstract Language" : "OABL",
"Other Copyright Information" : "OCI",
"Other ID" : "OID",
"Other Term" : "OT",
"Other Term Owner" : "OTO",
"Owner" : "OWN",
"Pagination" : "PG",
"Personal Name as Subject" : "PS",
"Full Personal Name as Subject" : "FPS",
"Place of Publication" : "PL",
"Publication History Status" : "PHST",
"Publication Status" : "PST",
"Publication Type" : "PT",
"Publishing Model" : "PUBM",
"PubMed Central Identifier" : "PMC",
"PubMed Central Release" : "PMCR",
"PubMed Unique Identifier" : "PMID",
"Registry Number/EC Number" : "RN",
"Substance Name" : "NM",
"Secondary Source ID" : "SI",
"Source" : "SO",
"Space Flight Mission" : "SFM",
"Status" : "STAT",
"Subset" : "SB",
"title" : "TI",
"Transliterated Title" : "TT",
"Volume" : "VI",
"Volume Title" : "VTI",
"Comment in" : "CIN",
"Erratum in" : "EIN",
"Erratum for" : "EFR",
"Corrected and Republished in" : "CRI",
"Corrected and Republished from" : "CRF",
"Dataset described in" : "DDIN",
"Dataset use reported in" : "DRIN",
"Partial retraction in" : "PRIN",
"Partial retraction of" : "PROF",
"Republished in" : "RPI",
"Republished from" : "RPF",
"Retraction in" : "RIN",
"Retraction of" : "ROF",
"Update in" : "UIN",
"Update of" : "UOF",
"Summary for patients in" : "SPIN",
"Original report in" : "ORI",
}

tagNameConverterDict = makeBiDirectional(tagNameDict)
